### ISSUE TITLE
First request for exported spreadsheet causes an exception within apache

### ISSUE THREAD

**Issue by danfrz** [UMM-CSci-3601-S17/digital-display-garden-iteration-3-revolverenguardia#16]
```
ERROR:  ''
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@af4daf0
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at umm3601.digitalDisplayGarden.FeedbackWriter.complete(FeedbackWriter.java:249)
Related to #12 
```

**Comment by danfrz** [comment]
"Fixed" by eaac017951ae0a6c2cce7864ef7029bc0f25d81c
